// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent 注册信息
type AgentRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegister) Reset() {
	*x = AgentRegister{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegister) ProtoMessage() {}

func (x *AgentRegister) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegister.ProtoReflect.Descriptor instead.
func (*AgentRegister) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRegister) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentRegister) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentRegister) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AgentRegister) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentRegister) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentRegister) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 心跳消息
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     *Timestamp             `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// 从管理平台到 Agent 的消息
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_RegisterResponse
	//	*ServerMessage_HeartbeatAck
	//	*ServerMessage_TaskRequest
	//	*ServerMessage_InstallPlugin
	//	*ServerMessage_UninstallPlugin
	//	*ServerMessage_ListPlugins
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetRegisterResponse() *Response {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *ServerMessage) GetHeartbeatAck() *Response {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *ServerMessage) GetTaskRequest() *TaskRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_TaskRequest); ok {
			return x.TaskRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetInstallPlugin() *InstallPluginRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_InstallPlugin); ok {
			return x.InstallPlugin
		}
	}
	return nil
}

func (x *ServerMessage) GetUninstallPlugin() *UninstallPluginRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_UninstallPlugin); ok {
			return x.UninstallPlugin
		}
	}
	return nil
}

func (x *ServerMessage) GetListPlugins() *ListPluginsRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_ListPlugins); ok {
			return x.ListPlugins
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_RegisterResponse struct {
	RegisterResponse *Response `protobuf:"bytes,1,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type ServerMessage_HeartbeatAck struct {
	HeartbeatAck *Response `protobuf:"bytes,2,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type ServerMessage_TaskRequest struct {
	TaskRequest *TaskRequest `protobuf:"bytes,3,opt,name=task_request,json=taskRequest,proto3,oneof"` // 新增：任务下发
}

type ServerMessage_InstallPlugin struct {
	InstallPlugin *InstallPluginRequest `protobuf:"bytes,4,opt,name=install_plugin,json=installPlugin,proto3,oneof"` // 插件安装
}

type ServerMessage_UninstallPlugin struct {
	UninstallPlugin *UninstallPluginRequest `protobuf:"bytes,5,opt,name=uninstall_plugin,json=uninstallPlugin,proto3,oneof"` // 插件卸载
}

type ServerMessage_ListPlugins struct {
	ListPlugins *ListPluginsRequest `protobuf:"bytes,6,opt,name=list_plugins,json=listPlugins,proto3,oneof"` // 列出插件
}

func (*ServerMessage_RegisterResponse) isServerMessage_Message() {}

func (*ServerMessage_HeartbeatAck) isServerMessage_Message() {}

func (*ServerMessage_TaskRequest) isServerMessage_Message() {}

func (*ServerMessage_InstallPlugin) isServerMessage_Message() {}

func (*ServerMessage_UninstallPlugin) isServerMessage_Message() {}

func (*ServerMessage_ListPlugins) isServerMessage_Message() {}

// 从 Agent 到管理平台的消息
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_TaskResult
	//	*AgentMessage_TaskLog
	//	*AgentMessage_InstallPluginResponse
	//	*AgentMessage_UninstallPluginResponse
	//	*AgentMessage_ListPluginsResponse
	Message       isAgentMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentMessage) GetMessage() isAgentMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AgentMessage) GetRegister() *AgentRegister {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *AgentMessage) GetTaskLog() *TaskLog {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_TaskLog); ok {
			return x.TaskLog
		}
	}
	return nil
}

func (x *AgentMessage) GetInstallPluginResponse() *InstallPluginResponse {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_InstallPluginResponse); ok {
			return x.InstallPluginResponse
		}
	}
	return nil
}

func (x *AgentMessage) GetUninstallPluginResponse() *UninstallPluginResponse {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_UninstallPluginResponse); ok {
			return x.UninstallPluginResponse
		}
	}
	return nil
}

func (x *AgentMessage) GetListPluginsResponse() *ListPluginsResponse {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_ListPluginsResponse); ok {
			return x.ListPluginsResponse
		}
	}
	return nil
}

type isAgentMessage_Message interface {
	isAgentMessage_Message()
}

type AgentMessage_Register struct {
	Register *AgentRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,3,opt,name=task_result,json=taskResult,proto3,oneof"` // 新增：任务结果
}

type AgentMessage_TaskLog struct {
	TaskLog *TaskLog `protobuf:"bytes,4,opt,name=task_log,json=taskLog,proto3,oneof"` // 新增：任务日志
}

type AgentMessage_InstallPluginResponse struct {
	InstallPluginResponse *InstallPluginResponse `protobuf:"bytes,5,opt,name=install_plugin_response,json=installPluginResponse,proto3,oneof"` // 插件安装响应
}

type AgentMessage_UninstallPluginResponse struct {
	UninstallPluginResponse *UninstallPluginResponse `protobuf:"bytes,6,opt,name=uninstall_plugin_response,json=uninstallPluginResponse,proto3,oneof"` // 插件卸载响应
}

type AgentMessage_ListPluginsResponse struct {
	ListPluginsResponse *ListPluginsResponse `protobuf:"bytes,7,opt,name=list_plugins_response,json=listPluginsResponse,proto3,oneof"` // 列出插件响应
}

func (*AgentMessage_Register) isAgentMessage_Message() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Message() {}

func (*AgentMessage_TaskResult) isAgentMessage_Message() {}

func (*AgentMessage_TaskLog) isAgentMessage_Message() {}

func (*AgentMessage_InstallPluginResponse) isAgentMessage_Message() {}

func (*AgentMessage_UninstallPluginResponse) isAgentMessage_Message() {}

func (*AgentMessage_ListPluginsResponse) isAgentMessage_Message() {}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x05proto\x1a\x12proto/common.proto\x1a\x10proto/task.proto\x1a\x12proto/plugin.proto\"\x94\x01\n" +
	"\rAgentRegister\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"V\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12.\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x10.proto.TimestampR\ttimestamp\"\x9d\x03\n" +
	"\rServerMessage\x12>\n" +
	"\x11register_response\x18\x01 \x01(\v2\x0f.proto.ResponseH\x00R\x10registerResponse\x126\n" +
	"\rheartbeat_ack\x18\x02 \x01(\v2\x0f.proto.ResponseH\x00R\fheartbeatAck\x127\n" +
	"\ftask_request\x18\x03 \x01(\v2\x12.proto.TaskRequestH\x00R\vtaskRequest\x12D\n" +
	"\x0einstall_plugin\x18\x04 \x01(\v2\x1b.proto.InstallPluginRequestH\x00R\rinstallPlugin\x12J\n" +
	"\x10uninstall_plugin\x18\x05 \x01(\v2\x1d.proto.UninstallPluginRequestH\x00R\x0funinstallPlugin\x12>\n" +
	"\flist_plugins\x18\x06 \x01(\v2\x19.proto.ListPluginsRequestH\x00R\vlistPluginsB\t\n" +
	"\amessage\"\xea\x03\n" +
	"\fAgentMessage\x122\n" +
	"\bregister\x18\x01 \x01(\v2\x14.proto.AgentRegisterH\x00R\bregister\x120\n" +
	"\theartbeat\x18\x02 \x01(\v2\x10.proto.HeartbeatH\x00R\theartbeat\x124\n" +
	"\vtask_result\x18\x03 \x01(\v2\x11.proto.TaskResultH\x00R\n" +
	"taskResult\x12+\n" +
	"\btask_log\x18\x04 \x01(\v2\x0e.proto.TaskLogH\x00R\ataskLog\x12V\n" +
	"\x17install_plugin_response\x18\x05 \x01(\v2\x1c.proto.InstallPluginResponseH\x00R\x15installPluginResponse\x12\\\n" +
	"\x19uninstall_plugin_response\x18\x06 \x01(\v2\x1e.proto.UninstallPluginResponseH\x00R\x17uninstallPluginResponse\x12P\n" +
	"\x15list_plugins_response\x18\a \x01(\v2\x1a.proto.ListPluginsResponseH\x00R\x13listPluginsResponseB\t\n" +
	"\amessage2H\n" +
	"\fAgentService\x128\n" +
	"\aConnect\x12\x13.proto.AgentMessage\x1a\x14.proto.ServerMessage(\x010\x01B.Z,github.com/yourusername/agent-platform/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_agent_proto_goTypes = []any{
	(*AgentRegister)(nil),           // 0: proto.AgentRegister
	(*Heartbeat)(nil),               // 1: proto.Heartbeat
	(*ServerMessage)(nil),           // 2: proto.ServerMessage
	(*AgentMessage)(nil),            // 3: proto.AgentMessage
	(*Timestamp)(nil),               // 4: proto.Timestamp
	(*Response)(nil),                // 5: proto.Response
	(*TaskRequest)(nil),             // 6: proto.TaskRequest
	(*InstallPluginRequest)(nil),    // 7: proto.InstallPluginRequest
	(*UninstallPluginRequest)(nil),  // 8: proto.UninstallPluginRequest
	(*ListPluginsRequest)(nil),      // 9: proto.ListPluginsRequest
	(*TaskResult)(nil),              // 10: proto.TaskResult
	(*TaskLog)(nil),                 // 11: proto.TaskLog
	(*InstallPluginResponse)(nil),   // 12: proto.InstallPluginResponse
	(*UninstallPluginResponse)(nil), // 13: proto.UninstallPluginResponse
	(*ListPluginsResponse)(nil),     // 14: proto.ListPluginsResponse
}
var file_proto_agent_proto_depIdxs = []int32{
	4,  // 0: proto.Heartbeat.timestamp:type_name -> proto.Timestamp
	5,  // 1: proto.ServerMessage.register_response:type_name -> proto.Response
	5,  // 2: proto.ServerMessage.heartbeat_ack:type_name -> proto.Response
	6,  // 3: proto.ServerMessage.task_request:type_name -> proto.TaskRequest
	7,  // 4: proto.ServerMessage.install_plugin:type_name -> proto.InstallPluginRequest
	8,  // 5: proto.ServerMessage.uninstall_plugin:type_name -> proto.UninstallPluginRequest
	9,  // 6: proto.ServerMessage.list_plugins:type_name -> proto.ListPluginsRequest
	0,  // 7: proto.AgentMessage.register:type_name -> proto.AgentRegister
	1,  // 8: proto.AgentMessage.heartbeat:type_name -> proto.Heartbeat
	10, // 9: proto.AgentMessage.task_result:type_name -> proto.TaskResult
	11, // 10: proto.AgentMessage.task_log:type_name -> proto.TaskLog
	12, // 11: proto.AgentMessage.install_plugin_response:type_name -> proto.InstallPluginResponse
	13, // 12: proto.AgentMessage.uninstall_plugin_response:type_name -> proto.UninstallPluginResponse
	14, // 13: proto.AgentMessage.list_plugins_response:type_name -> proto.ListPluginsResponse
	3,  // 14: proto.AgentService.Connect:input_type -> proto.AgentMessage
	2,  // 15: proto.AgentService.Connect:output_type -> proto.ServerMessage
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	file_proto_common_proto_init()
	file_proto_task_proto_init()
	file_proto_plugin_proto_init()
	file_proto_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*ServerMessage_RegisterResponse)(nil),
		(*ServerMessage_HeartbeatAck)(nil),
		(*ServerMessage_TaskRequest)(nil),
		(*ServerMessage_InstallPlugin)(nil),
		(*ServerMessage_UninstallPlugin)(nil),
		(*ServerMessage_ListPlugins)(nil),
	}
	file_proto_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_TaskResult)(nil),
		(*AgentMessage_TaskLog)(nil),
		(*AgentMessage_InstallPluginResponse)(nil),
		(*AgentMessage_UninstallPluginResponse)(nil),
		(*AgentMessage_ListPluginsResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
